// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { JobMarketV2$Type } from "./JobMarketV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["JobMarketV2"]: JobMarketV2$Type;
    ["contracts/JobMarketV2.sol:JobMarketV2"]: JobMarketV2$Type;
  }

  interface ContractTypesMap {
    ["JobMarketV2"]: GetContractReturnType<JobMarketV2$Type["abi"]>;
    ["contracts/JobMarketV2.sol:JobMarketV2"]: GetContractReturnType<JobMarketV2$Type["abi"]>;
  }
}
