// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Escrow$Type } from "./Escrow";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Escrow"]: Escrow$Type;
    ["contracts/Escrow.sol:Escrow"]: Escrow$Type;
  }

  interface ContractTypesMap {
    ["Escrow"]: GetContractReturnType<Escrow$Type["abi"]>;
    ["contracts/Escrow.sol:Escrow"]: GetContractReturnType<Escrow$Type["abi"]>;
  }
}
