// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AgentRegistryV2$Type } from "./AgentRegistryV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AgentRegistryV2"]: AgentRegistryV2$Type;
    ["contracts/AgentRegistryV2.sol:AgentRegistryV2"]: AgentRegistryV2$Type;
  }

  interface ContractTypesMap {
    ["AgentRegistryV2"]: GetContractReturnType<AgentRegistryV2$Type["abi"]>;
    ["contracts/AgentRegistryV2.sol:AgentRegistryV2"]: GetContractReturnType<AgentRegistryV2$Type["abi"]>;
  }
}
