// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { X402Payment$Type } from "./X402Payment";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["X402Payment"]: X402Payment$Type;
    ["contracts/X402Payment.sol:X402Payment"]: X402Payment$Type;
  }

  interface ContractTypesMap {
    ["X402Payment"]: GetContractReturnType<X402Payment$Type["abi"]>;
    ["contracts/X402Payment.sol:X402Payment"]: GetContractReturnType<X402Payment$Type["abi"]>;
  }
}
