// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { JobMarket$Type } from "./JobMarket";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["JobMarket"]: JobMarket$Type;
    ["contracts/JobMarket.sol:JobMarket"]: JobMarket$Type;
  }

  interface ContractTypesMap {
    ["JobMarket"]: GetContractReturnType<JobMarket$Type["abi"]>;
    ["contracts/JobMarket.sol:JobMarket"]: GetContractReturnType<JobMarket$Type["abi"]>;
  }
}
