// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AgentRegistry$Type } from "./AgentRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AgentRegistry"]: AgentRegistry$Type;
    ["contracts/AgentRegistry.sol:AgentRegistry"]: AgentRegistry$Type;
  }

  interface ContractTypesMap {
    ["AgentRegistry"]: GetContractReturnType<AgentRegistry$Type["abi"]>;
    ["contracts/AgentRegistry.sol:AgentRegistry"]: GetContractReturnType<AgentRegistry$Type["abi"]>;
  }
}
